apiVersion: v1
kind: PersistentVolume
metadata:
  name: local
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local2
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local3
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/data"
---
